initial config

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,14 +10,22 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME"
 
-# Download tar.gz file to the download directory
+# Download binary to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
+download_release "$ASDF_INSTALL_VERSION" "$release_file.sha256"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+# verify checksum
+checksum=$(cat "$release_file.sha256")
+checksum_file=$(sha256sum "$release_file" | awk '{print $1}')
 
-# Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
+if [ "$checksum" != "$checksum_file" ]; then
+	echo "Checksum verification failed"
+	exit 1
+else
+	echo "Checksum verification succeeded"
+fi
+
+# Make the binary executable
+chmod +x "$ASDF_DOWNLOAD_PATH/$TOOL_NAME"
